### ISSUE TITLE
More detailed install instructions?

### ISSUE THREAD

**Issue by dennym** [Sliman4/bevy_slinet#2]
Hey there,

no idea how active you are with the lib and what your plans are for the future? Are more detailed install instruction for a regular bevy project would be lovely.

I use scenes as plugins and I can easily use any other rust package with `use package_name:{....`. Unfortunately this does not work for slinet :/ Tried some cherry picking from the `cargo.toml` but didn't change anything on the errors I get.

```
error[E0432]: unresolved import `bevy_slinet::client`
 --> src/scenes/world.rs:5:18
  |
5 | use bevy_slinet::client::{ClientPlugin, ConnectionEstablishEvent, PacketReceiveEvent};
  |                  ^^^^^^ could not find `client` in `bevy_slinet`

error[E0432]: unresolved import `bevy_slinet::protocols::tcp`
 --> src/scenes/world.rs:7:29
  |
7 | use bevy_slinet::protocols::tcp::TcpProtocol;
  |                             ^^^ could not find `tcp` in `protocols`

error[E0432]: unresolved import `bevy_slinet::serializers::bincode`
 --> src/scenes/world.rs:8:31
  |
8 | use bevy_slinet::serializers::bincode::{BincodeSerializer, DefaultOptions};
  |                               ^^^^^^^ could not find `bincode` in `serializers`

```

**Comment by Sliman4** [comment]
When I initially made the first version, I wanted to make it work on wasm, that's why everything is feature-gated. bevy_slinet is useless with just default features (unless you want to implement your own protocol and serializer), so you need to enable crate features: `client`, `protocol_tcp`, and `serializer_bincode`.

Added a notice about that in README.md.
